### ISSUE TITLE
please fix model classes

### ISSUE THREAD

**Issue by warrior2015** [Hariofspades/Dagger-2-Advanced#4]
Can you please fix model class for dob and registered. Application is not loading.

**Comment by SamuelaAnastasi** [comment]
Hi @warrior2015 
I solved it by calling a previous version of API at `RandomUsersApi` interface:
```
public interface RandomUsersApi {

    @GET("api/1.1/")
    Call<RandomUsers> getRandomUsers(@Query("results") int size);
}
```
Hope it helps.

**Comment by ivoronezhtsev** [comment]
This is missing classes Dob and Registered. Rename extension to *.patch and apply via VCS->Apply patch in Android studio.
[Patch.txt](https://github.com/Hariofspades/Dagger-2-Advanced/files/2612250/Patch.txt)
May be exists some solution to ignore new unknown fileds?

**Comment by Hariofspades** [comment]
Merged the fix
