### ISSUE TITLE
App does not displaying anything

### ISSUE THREAD

**Issue by sushantchauhan08** [Hariofspades/Dagger-2-Advanced#5]

**Comment by georgeRCluj** [comment]
Hi, if you want to make it work, do the following steps:
- in MainActivity in method "afterActivityLevelComponent()" add a last line of code "picasso = RandomUserApplication.get(this).getRandomUserApplicationComponent().getPicasso();"

That's all and works like a charm!
George

**Comment by astend** [comment]
> Hi, if you want to make it work, do the following steps:
> 
> * in MainActivity in method "afterActivityLevelComponent()" add a last line of code "picasso = RandomUserApplication.get(this).getRandomUserApplicationComponent().getPicasso();"
> 
> That's all and works like a charm!
> George

its not working (for me, because received json file is changed).
To quickly solve this problem, go to the Result class and comment next:
`/*@SerializedName("location")
    @Expose
    private Location location;*/`
`/*@SerializedName("dob")
    @Expose
    private String dob;
    @SerializedName("registered")
    @Expose
    private String registered;*/`

make changes into getters and setters and toString() method

**Comment by AlexanderSoftman** [comment]
Astend, you are right. API of website changed. I created [pull request](https://github.com/Hariofspades/Dagger-2-Advanced/pull/6) that will fix this.

**Comment by Hariofspades** [comment]
Thank you @AlexanderSoftman. Merged.
